name: Nodejs CI/CD

on:
    push:
        branches:
            - main
    pull_request:
         branches:
            - main


jobs:

    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install NodeJs v18.x
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
                cache: npm

            -   name: Install Dependencies 
                run: npm ci
            - name: Build
              run: npm run build --if-present
            -   name: Test
                run: npm test --if-present

